### ISSUE TITLE
动漫屋解析失败

### ISSUE THREAD

**Issue by BlackHole1** [RebornQ/Cimoc#3]
在某些漫画里动漫屋会解析失败。如：元尊后面几章

**Comment by RebornQ** [comment]
@BlackHole1 去动漫屋网站看了一下，发现元尊后面是付费章节所以才会加载失败，这种付费观看的问题无力解决。但可以尝试换源，元尊的话目前漫画台、吹雪漫画、扑飞漫画都可以正常观看

**Comment by BlackHole1** [comment]
了解了。十分感谢
